### ISSUE TITLE
Is the day of the event a reading day?

### ISSUE THREAD

**Issue by Sevorg** [aljedaxi/readererer#1]
If you mark the day of event a non-reading day, the daily numbers change.
If event day is assumed to be a reading day, could consider displaying reading time on that day as well?

**Comment by aljedaxi** [comment]
not currently

**Comment by aljedaxi** [comment]
d'you think it's a good idea? i like the idea of nudging people towards better habits, and reading your assigned text the day of definitely isn't

**Comment by Sevorg** [comment]
yeah, agree having it be a reading day is not ideal.

**Comment by Sevorg** [comment]
I guess the daily totals may be changing because of issue #3. :)

**Comment by aljedaxi** [comment]
wrong issue lol

**Comment by aljedaxi** [comment]
right issue this time
