### ISSUE TITLE
non-reading days in the past affect daily times

### ISSUE THREAD

**Issue by Sevorg** [aljedaxi/readererer#3]
e.g., Event is marked as Jan 15. Marking Jan 1 and 2 as non-reading days affects the daily times calculation.
kinda trivial, but could be marked by accident

**Comment by aljedaxi** [comment]
oh fuck yeah that's deffo a bug
@aljedaxi can u fix this?

**Comment by aljedaxi** [comment]
fixed in https://github.com/aljedaxi/readererer/commit/cf3fef59974dec0bf8308e9ee95ffe4ca32c9e24
